platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'

# @#$ You need to change targe name to your [Project Name]
target 'rn_unimodule_template' do
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTText',
        'RCTNetwork',
        'RCTWebSocket',
        'RCTAnimation',
        'RCTImage',
    ]

    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

    # use unimodules
    use_unimodules!

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == "React"
                target.remove_from_project
            end
        end
    end

    # @#$ You need to change targe name to your [Project Name]+"Test"
    target 'rn_unimodule_templateTests' do
        inherit! :search_paths
        # Pods for testing
    end

end
